NDefines.NMilitary.NUKE_MIN_DAMAGE_PERCENT = 0.9;
NDefines.NMilitary.NUKE_MAX_DAMAGE_PERCENT = 1.2;
NDefines.NMilitary.NUKE_DELAY_HOURS = 12;
NDefines.NCountry.NUCLEAR_BOMB_DROP_WAR_SUPPORT_EFFECT_MAX_INFRA = 0.35;
NDefines.NCountry.NUCLEAR_BOMB_DROP_WAR_SUPPORT_EFFECT_MAX_VP = 1;